{
  "openapi": "3.0.3",
  "info": {
    "title": "Todolist RESTful API",
    "version": "1",
    "description": "OpenAPI for Todolist RESTful API",
    "contact": {
      "name": "Danar Gumilang Putera",
      "email": "danar.g.putera@gmail.com",
      "url": "https://github.com/bungdanar"
    },
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/license/mit/"
    }
  },
  "servers": [
    {
      "description": "Todolist RESTful API Server",
      "url": "http://{environment}.localhost:5000/api/v1",
      "variables": {
        "environment": {
          "description": "Server Environment",
          "default": "dev",
          "enum": [
            "dev",
            "qa",
            "prod"
          ]
        }
      }
    }
  ],
  "externalDocs": {
    "description": "Github Bung Danar",
    "url": "https://github.com/bungdanar"
  },
  "paths": {
    "/todolist": {
      "get": {
        "security": [
          {
            "TodolistAuth": []
          }
        ],
        "tags": [
          "Todolist"
        ],
        "summary": "Get all todolist",
        "description": "Get all active todolist by default",
        "parameters": [
          {
            "name": "include_done",
            "in": "query",
            "required": false,
            "description": "Does include done todolist",
            "schema": {
              "type": "boolean",
              "nullable": true,
              "default": false
            }
          },
          {
            "name": "name",
            "in": "query",
            "required": false,
            "description": "Filter todolist by name",
            "schema": {
              "type": "string",
              "nullable": true,
              "minLength": 1,
              "maxLength": 100
            },
            "examples": {
              "java": {
                "value": "Learning Java",
                "description": "Example for name query"
              },
              "php": {
                "value": "Learning PHP",
                "description": "Example for name query"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully get all todolist",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ArrayTodolist"
                },
                "examples": {
                  "success": {
                    "description": "Example for successfully get all todolist",
                    "value": [
                      {
                        "id": "1",
                        "name": "Learning Java",
                        "priority": 3,
                        "tags": [
                          "Java",
                          "Programming"
                        ]
                      },
                      {
                        "id": "2",
                        "name": "Learning PHP",
                        "priority": 2,
                        "tags": [
                          "PHP",
                          "Programming"
                        ]
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "TodolistAuth": []
          }
        ],
        "tags": [
          "Todolist"
        ],
        "summary": "Create new todolist",
        "description": "Create new todolist to database",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateOrUpdateTodolist"
              },
              "examples": {
                "java": {
                  "description": "Example for creating todolist",
                  "value": {
                    "name": "Learning Java",
                    "priority": 3,
                    "tags": [
                      "Java",
                      "Programming"
                    ]
                  }
                },
                "php": {
                  "description": "Example for creating todolist",
                  "value": {
                    "name": "Learning PHP",
                    "priority": 2,
                    "tags": [
                      "PHP",
                      "Programming"
                    ]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successfully create todolist",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Todolist"
                },
                "examples": {
                  "success": {
                    "description": "Example for successfully create todolist",
                    "value": {
                      "id": "1",
                      "name": "Learning Java",
                      "priority": 3,
                      "tags": [
                        "Java",
                        "Programming"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/todolist/{todolistId}": {
      "put": {
        "security": [
          {
            "TodolistAuth": []
          }
        ],
        "tags": [
          "Todolist"
        ],
        "summary": "Update existing todolist",
        "description": "Update existing todolist in database",
        "parameters": [
          {
            "$ref": "#/components/parameters/TodolistId"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateOrUpdateTodolist"
              },
              "examples": {
                "java": {
                  "description": "Example for creating todolist",
                  "value": {
                    "name": "Learning Java",
                    "priority": 3,
                    "tags": [
                      "Java",
                      "Programming"
                    ]
                  }
                },
                "php": {
                  "description": "Example for creating todolist",
                  "value": {
                    "name": "Learning PHP",
                    "priority": 2,
                    "tags": [
                      "PHP",
                      "Programming"
                    ]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successfully update todolist",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Todolist"
                },
                "examples": {
                  "success": {
                    "description": "Example for successfully update todolist",
                    "value": {
                      "id": "1",
                      "name": "Learning Java",
                      "priority": 3,
                      "tags": [
                        "Java",
                        "Programming"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "TodolistAuth": []
          }
        ],
        "tags": [
          "Todolist"
        ],
        "summary": "Delete existing todolist",
        "description": "Delete existing todolist in database",
        "parameters": [
          {
            "$ref": "#/components/parameters/TodolistId"
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully delete todolist",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    }
                  }
                },
                "examples": {
                  "success": {
                    "description": "Example for successfully delete todolist",
                    "value": {
                      "success": true
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Failed delete because not found todolist",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    }
                  }
                },
                "examples": {
                  "failed": {
                    "description": "Example for failed delete todolist",
                    "value": {
                      "success": false
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "TodolistAuth": {
        "description": "Authentication for Todolist RESTful API",
        "type": "apiKey",
        "in": "header",
        "name": "X-API-Key"
      }
    },
    "parameters": {
      "TodolistId": {
        "name": "todolistId",
        "in": "path",
        "required": true,
        "description": "Todolist id for updated",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 100
        },
        "examples": {
          "java": {
            "description": "Sample todolist id",
            "value": "1"
          },
          "php": {
            "description": "Sample todolist id",
            "value": "2"
          }
        }
      }
    },
    "schemas": {
      "Todolist": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "priority": {
            "type": "number",
            "format": "int32"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "CreateOrUpdateTodolist": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1,
            "required": true
          },
          "priority": {
            "type": "integer",
            "format": "int32",
            "required": true,
            "default": 1
          },
          "tags": {
            "type": "array",
            "required": false,
            "minItems": 1,
            "items": {
              "type": "string",
              "minLength": 1
            }
          }
        }
      },
      "ArrayTodolist": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Todolist"
        }
      }
    }
  }
}